name: retrain-air

on:
  schedule:
    - cron: '30 17 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"
        cache: "pip"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/app/trafficData/requirements_retrain.txt
    - name: Run the retrain code for air data to get updated air information
      env:
          MONGO_USER_NAME: ${{ secrets.MONGO_USER_NAME }}
          MONGO_PASSWORD: ${{secrets.MONGO_PASSWORD}}
      run: |
        python backend/app/trafficData/retrainModelAir.py
